/* QCM de validation — 10 questions (kit de préparation, §5). Une seule bonne réponse par question. */
window.QCM=[
{q:"Quelle mesure privilégier pour prévenir une chute ?",o:["Harnais systématique","Protection collective adaptée","Simple consigne orale"],a:1,e:"La protection collective est recherchée en priorité sur la protection individuelle (principe général de prévention, L. 4121-2)."},
{q:"Un harnais antichute utilisé seul protège-t-il contre une chute ?",o:["Oui","Non","Seulement sur toiture"],a:1,e:"Le harnais n'est qu'un composant : il faut un système complet (ancrage, liaison, absorption) adapté."},
{q:"Avant d'utiliser un ancrage provisoire, il faut :",o:["Choisir le point le plus proche","Valider l'ancrage, son support et la configuration","Tester par traction manuelle"],a:1,e:"Un point disponible n'est pas forcément un ancrage utilisable : support et configuration sont validés par une personne compétente."},
{q:"Le tirant d'air sert à vérifier :",o:["La résistance du casque","L'espace libre nécessaire sous l'utilisateur","La météo"],a:1,e:"Il s'agit de la hauteur libre nécessaire sous l'utilisateur pour éviter le choc avec le sol ou un obstacle."},
{q:"Un connecteur dont le verrouillage est défectueux doit être :",o:["Utilisé avec prudence","Réparé sur place sans notice","Écarté du service"],a:2,e:"Tout équipement douteux est retiré du service et signalé."},
{q:"Avec un système d'arrêt de chute, le travailleur peut-il rester seul ?",o:["Oui","Non","Seulement pour une tâche courte"],a:1,e:"Le travail n'est jamais isolé : un secours doit pouvoir être apporté à temps (R. 4323-61)."},
{q:"Avant chaque utilisation d'un EPI antichute, l'utilisateur doit :",o:["Vérifier l'état et les informations de suivi","Se fier à sa couleur","Attendre la vérification annuelle"],a:0,e:"Le contrôle avant emploi complète la vérification périodique, il ne la remplace pas."},
{q:"Si la météo rend le travail dangereux :",o:["On accélère","On suspend ou on adapte l'intervention","On utilise une longe plus longue"],a:1,e:"Les travaux temporaires en hauteur ne sont pas réalisés lorsque les conditions météo ou de l'environnement compromettent la sécurité (R. 4323-68)."},
{q:"Après une chute arrêtée par un EPI, il faut :",o:["Réutiliser le matériel si aucune déchirure n'est visible","Écarter le matériel selon la notice et déclencher le secours prévu","Terminer le travail"],a:1,e:"Le matériel ayant arrêté une chute est retiré du service ; le secours prévu est déclenché sans délai."},
{q:"Le plan de secours doit être :",o:["Défini avant l'intervention","Conçu après l'accident","Limité à un numéro de téléphone"],a:0,e:"Qui alerte, qui sécurise, qui intervient, avec quel matériel, par quel accès : tout est défini avant."}
];
