'use strict';
document.head.insertAdjacentHTML('beforeend','<style>@media(max-width:720px){header button{position:static;margin-left:auto}header div{order:2}header button{order:3}aside nav{max-height:210px;overflow:auto}}@media print{.bonifay-media{break-before:page;break-inside:auto!important}.bonifay-media>.eyebrow{display:none}.bonifay-media>.grid{display:block!important}.bonifay-media figure{break-before:page;break-inside:avoid;margin:0!important}.bonifay-media figure:first-child{break-before:auto}.bonifay-media img{max-height:165mm;width:auto!important;max-width:100%;display:block;margin:auto}.bonifay-media a[download]{display:none}.bonifay-media figcaption{break-before:auto!important;break-after:auto!important}}</style>');
// Adaptation isolée : aucune modification du support DGA original.
const bonifayHome=home,bonifayTrainer=trainer,bonifayVisuals=visuals;
const faq='https://www.inrs.fr/risques/electriques/habilitation-electrique-foire-aux-questions';
D.sources.push(['INRS · vérification Bonifay du 10 octobre 2026',faq,'Périmètres B0/H0/H0V, limites cumulatives BS et manœuvres BE.']);
D.modules[0].scenario='Vous reprenez vos missions après votre précédent stage. Une nouvelle tâche de raccordement vous est confiée : votre titre actuel couvre-t-il réellement cette opération ?';
D.modules[0].sections.push(['Recyclage : confronter les habitudes au périmètre','Présenter les opérations réellement réalisées depuis la dernière formation, les écarts, les incidents et les changements de matériel. Relire le titre en cours et ses limites. La réussite du recyclage ne renouvelle pas automatiquement le titre : le formateur émet un avis individualisé et l’employeur décide.']);
const bonifayCases=[
 ['Zone de stockage','Une rallonge présente une gaine entaillée ; le matériel alimenté fonctionne encore.','Suspendre l’utilisation selon les consignes, empêcher une réutilisation et signaler. Aucun essai supplémentaire pour confirmer le défaut.',2],
 ['Circulation de matériaux','Un matériau long doit franchir une zone balisée à proximité d’un équipement électrique.','Suspendre le déplacement et revoir le trajet avec le responsable. Tenir compte du matériau et de tous ses mouvements ; ne pas déplacer le balisage.',4],
 ['Éclairage','Une lampe doit être remplacée. Le support est détérioré et le circuit mal identifié.','Ne pas commencer. Obtenir une identification fiable et faire traiter la détérioration. Le remplacement n’est admissible que dans les conditions du titre et de l’intervention BS.',5],
 ['Prise de courant','Une prise doit être déplacée pour un équipement supplémentaire.','Une modification ou un déplacement de circuit dépasse le remplacement à l’identique. Demander le relais compétent.',5],
 ['Commande d’équipement','Un ordre de mise en marche désigne un appareil dont le repère est effacé.','Obtenir une identification fiable avant toute manœuvre. Ne pas choisir par ressemblance.',7],
 ['Déclenchement répété','Après un réarmement autorisé, la protection déclenche de nouveau.','Suspendre les tentatives, décrire les faits et rendre compte. Aucun diagnostic improvisé ni neutralisation de protection.',7],
 ['Nettoyage','Un nettoyage humide est demandé près d’une enveloppe électrique ouverte.','Suspendre l’activité et faire rétablir les conditions de sécurité. B0 n’autorise pas une intervention électrique.',4],
 ['Sources multiples','L’installation principale est coupée ; une alimentation de secours reste possible.','Faire identifier toutes les sources. Une coupure apparente et un voyant éteint ne prouvent pas l’absence de tension.',6]
];
V6_CASES.splice(0,V6_CASES.length,...bonifayCases);
const bonifayLinks=()=>`<div class="row"><a class="button primary" href="../evaluation/">Évaluation finale</a><a class="button" href="../livret/livret-bonifay.pdf">Livret PDF</a><a class="button" href="../">Accueil de session</a></div>`;
home=function(){bonifayHome();main.insertAdjacentHTML('afterbegin',`<section class="card"><p class="eyebrow">BONIFAY · LA GARDE · 12–13 OCTOBRE 2026</p><h2>Réactiver · corriger les habitudes · démontrer</h2><p>Recyclage B0 · H0/H0V · BS · BE Manœuvre — 6 participants. Les situations ci-dessous sont des exercices génériques, sans description présumée des installations du client.</p>${bonifayLinks()}<ol><li>Présenter ses missions et son retour d’expérience.</li><li>Réactiver les règles et traiter les écarts avec les huit séquences.</li><li>Réaliser les ateliers et une évaluation individuelle par symbole.</li></ol><p class="muted">Le libellé administratif « BE/HE BS » ne vaut pas ajout d’une préparation HE Manœuvre : les symboles de la liste de mission sont B0 H0V, BS et BE Manœuvre.</p></section>`);};
trainer=function(){bonifayTrainer();const cards=main.querySelectorAll('.card');for(const c of cards){if(c.querySelector('h2')?.textContent.includes('Déroulé proposé'))c.innerHTML=`<h2>Déroulé de recyclage · 6 participants</h2><div class="callout"><b>Écart documentaire à lever avec Consul Team.</b> L’ordre de mission annonce 10,5 h. Les créneaux 12/10 08:30–12:00 et 13:30–16:30, puis 13/10 08:30–12:00 représentent 10 h avant toute pause supplémentaire. Ne pas inventer une demi-heure : conserver les horaires reçus, faire confirmer l’ajustement et reporter la durée réellement réalisée.</div><table><thead><tr><th>Créneau reçu</th><th>Objectifs et activités</th></tr></thead><tbody><tr><td>12/10 · 08:30–12:00</td><td>Accueil, titre et missions, retour d’expérience, positionnement, réactivation du socle et des zones B0/H0/H0V ; ateliers de repérage.</td></tr><tr><td>12/10 · 13:30–16:30</td><td>BS : préparation, limites, mise hors tension, VAT et remplacement à l’identique sur banc ; BE Manœuvre : ordre, appareil, état final, anomalie et compte rendu.</td></tr><tr><td>13/10 · 08:30–12:00</td><td>Réactivation, observations individuelles complémentaires, évaluation théorique, remédiation et réévaluation, bilan et avis par symbole.</td></tr></tbody></table><p>Organiser les rotations pour observer chacun. L’atelier HT est simulé et explicitement annoncé ; aucune opération réelle sur une installation HT du client n’est présumée.</p>`;}
main.insertAdjacentHTML('afterbegin',`<div class="callout"><b>Contrôle avant session :</b> titres en cours, opérations réellement confiées, prérequis du recyclage, prescriptions locales, moyens de TP et équipements. Ne joindre aucune liste nominative à ce site public.</div>`);};
const media=[
 ['bs-limites.svg','BS : les limites se vérifient ensemble','Seuils INRS, intervention hors tension, sans voisinage, sur circuit terminal ; aucun exécutant sous ses ordres.'],
 ['roles.svg','Choisir le bon rôle','Opération non électrique, intervention élémentaire ou manœuvre : trois périmètres distincts.'],
 ['vat-controles.svg','VAT : deux contrôles encadrent la vérification','Le résultat est non concluant si un contrôle de fonctionnement échoue.'],
 ['reperer.webp','Repérer avant d’agir','Illustration générée : enveloppe fermée, balisage et signalement. Aucune distance représentée à l’échelle.'],
 ['vat-dispositif.webp','VAT : dispositif générique','Illustration générée, sans modèle commercial ni certification revendiquée. Choix selon installation et notice.']
];
function bonifayMedia(){return `<section class="card bonifay-media"><p class="eyebrow">COMPLÉMENTS BONIFAY · 10 OCTOBRE 2026</p><h2>Planches de réactivation</h2><div class="grid">${media.map(([file,title,note])=>`<figure style="margin:0"><a href="assets/${file}" target="_blank" rel="noopener"><img loading="eager" src="assets/${file}" alt="${E(title)}" style="width:100%;height:auto;border:1px solid #d5dfeb;border-radius:12px"></a><figcaption><b>${E(title)}</b><p>${E(note)}</p><a href="assets/${file}" download>Télécharger le visuel</a></figcaption></figure>`).join('')}</div><p class="muted">Ouvrir une planche pour zoomer. Schémas originaux ; aucune reproduction de planches MémoForma. Les seuils et périmètres sont sourcés dans le registre de session.</p></section>`;}
visuals=function(){bonifayVisuals();main.insertAdjacentHTML('afterbegin',bonifayMedia());};
const bonifayBook=book;book=function(){bonifayBook();main.insertAdjacentHTML('beforeend',bonifayMedia());};
render();
